### ISSUE TITLE
Could not control thermostat from HA

### ISSUE THREAD

**Issue by alexeyklots** [Makave1i/terneo_thermostat#1]
Thanks for the plugin, I was able to setup it easily and can see all my thermostats in HA. 
The only problem is that I could not control them. For example when I tried to change the needed temperature via UI after few seconds it returns to the previous value. Also other things like turn off/on, mode changing are not working. 
Is there anything I can do to fix this?

From logs
`2020-03-09 10:14:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.terneo fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/terneo/climate.py", line 154, in update
    self.thermostat.update()
  File "/config/custom_components/terneo/thermostat.py", line 235, in update
    self._mode = self.get_mode(data)
  File "/config/custom_components/terneo/thermostat.py", line 190, in get_mode
    is_on = self.is_on()
  File "/config/custom_components/terneo/thermostat.py", line 129, in is_on
    r = self.post(json={"cmd": 1})
  File "/config/custom_components/terneo/thermostat.py", line 109, in post
    content = r.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting ',' delimiter or ']': line 1 column 331 (char 330)`

**Comment by rubic0day** [comment]
Same problem. But I don't have any error in my logs. Also I have "read-only" states for all objects from this integration.
![Screenshot_1](https://user-images.githubusercontent.com/54459037/79328139-3ef1c580-7f1e-11ea-8fae-8097077601b3.jpg)

**Comment by Makave1i** [comment]
I'm sorry for not responding a long time.

> The only problem is that I could not control them. For example when I tried to change the needed temperature via UI after few seconds it returns to the previous value. Also other things like turn off/on, mode changing are not working.
> Is there anything I can do to fix this?

Looks like your terneo firmware is 2.3, but I don't have device with that firmware and can't debug. Better update to 2.4 as soon as possible, which works much better with HA.

This error appears permanently or sometimes?

> Same problem. But I don't have any error in my logs. Also I have "read-only" states for all objects from this integration.

seems like they added validating `serial number` to requests, you can try update this component if didn't find yet anything better)

**Comment by alexeyklots** [comment]
Thanks for the reply, will check, recently my terneo devices were updated to 2.4 but my HA are in dead state now

**Comment by Makave1i** [comment]
> Also I have "read-only" states for all objects from this integration.

added `unique_id`, should work now

**Comment by rubic0day** [comment]
Nice work. It helped, thanks.

**Comment by galexpro** [comment]
Thanks for the plugin! I have Terneo SX - firmware version is 2.5 (raven4). 
I can see all parameters, but could not control thermostat from HA.  I don't have any error in my logs.

**Comment by venuel79** [comment]
> Thanks for the plugin! I have Terneo SX - firmware version is 2.5 (raven4). I can see all parameters, but could not control thermostat from HA. I don't have any error in my logs.

Heare totaly the same problems! Also same software. And it's so sad. I have 8 of them.... 😕

**Comment by Makave1i** [comment]
for unknown reason i can't update firmware on my device to 2.5 version, and can't test. maybe something was changed in the api. you can try to test forks, maybe it was fixed there...

**Comment by Makave1i** [comment]
btw, did you disabled LAn locking? TOTP authentication is not implemented in this plugin...

> If you don’t need to use authentication, or if you are using software version 2.3, you must disable LAn locking (androidBlock = 0).

https://terneo-api.readthedocs.io/ru/latest/en/safety.html

**Comment by venuel79** [comment]
> btw, did you disabled LAn locking? TOTP authentication is not implemented in this plugin...
> 
> > If you don’t need to use authentication, or if you are using software version 2.3, you must disable LAn locking (androidBlock = 0).
> 
> https://terneo-api.readthedocs.io/ru/latest/en/safety.html

I guess, blocking is OFF, if not, I can control it via app or not?  Discribe is bad fir my understanding on this company link. Maybe iam confused something also

**Comment by Makave1i** [comment]
just published new version, you can try to install from hacs now. maybe cleanup locally and install from the scratch.
